### PR TITLE
Standard VAE and Multinomial VAE notebooks correct typos

### PR DESCRIPTION
**Pull request by EvgeniaChroni**
### Checklist:

- [x] I have followed the [contribution guidelines](../CONTRIBUTING.md) and code style for this project.
- [ ] I have added tests covering my contributions.
- [ ] I have updated the documentation accordingly.
- [x] This PR is being made to `staging` and not `master`.

### CODE REVIEW

**Comment by miguelgfierro** [comment]
@EvgeniaChroni there has been a problem with your PR and it took code from other people. Would you please do a branch from the latest staging, make the changes, and then do a PR to staging again?

**Comment by EvgeniaChroni** [comment]
> @EvgeniaChroni there has been a problem with your PR and it took code from other people. Would you please do a branch from the latest staging, make the changes, and then do a PR to staging again?

Is everything ok now ?

**Review by miguelgfierro — APPROVED** [review]
LGTM

**Review by anargyri — APPROVED** [review]

**Comment by EvgeniaChroni** [comment]
Sorry for the late reply,

Do you still need to do that ?

**Pull request merged**
