### PR TITLE
Simplify AzureML test workflows

### PR DESCRIPTION
**Pull request by pradnyeshjoshi**
### Description

Nightly CPU/GPU/Spark/Unit test workflows for AzureML test pipeline had a lot of redundant code. Created a template workflow which is then reused inside the nightly CPU/GPU/Spark/Unit test workflows.
Workflow runs: Nightly [CPU](https://github.com/microsoft/recommenders/actions/runs/2624487293), [GPU](https://github.com/microsoft/recommenders/actions/runs/2624487292), [Spark](https://github.com/microsoft/recommenders/actions/runs/2624487296), [Unit](https://github.com/microsoft/recommenders/actions/runs/2624487295) tests

### Related Issues

#1760 

### Checklist:

- [x] I have followed the [contribution guidelines](../CONTRIBUTING.md) and code style for this project.
- [ ] I have added tests covering my contributions.
- [ ] I have updated the documentation accordingly.
- [x] This PR is being made to `staging branch` and not to `main branch`.

### CODE REVIEW

**Review by miguelgfierro — APPROVED** [review]
Really good

**Comment by simonzhaoms** [comment]
@pradnyeshjoshi There is a possibility that we can combine `azureml_cpu_nightly.yml`, `azureml_gpu_nightly.yml`, `azureml_spark_nightly.yml` and `azureml_unit_test.yml` into one single file.  Do you think whether it is better?

**Comment by miguelgfierro** [comment]
> There is a possibility that we can combine azureml_cpu_nightly.yml, azureml_gpu_nightly.yml, azureml_spark_nightly.yml

My understanding was that if we do this, we won't be able to track 3 different badges as we are doing here: https://github.com/microsoft/recommenders/tree/staging#azureml-nightly-build-status

Is this right Pradnyesh?

**Comment by pradnyeshjoshi** [comment]
> > There is a possibility that we can combine azureml_cpu_nightly.yml, azureml_gpu_nightly.yml, azureml_spark_nightly.yml
> 
> My understanding was that if we do this, we won't be able to track 3 different badges as we are doing here: https://github.com/microsoft/recommenders/tree/staging#azureml-nightly-build-status
> 
> Is this right Pradnyesh?

Yes, @simonzhaoms we decided to separate these workflows earlier to have different badges for each.

**Pull request merged**
