### PR TITLE
Replace SARSingleNode with SAR

### PR DESCRIPTION
**Pull request by simonzhaoms**
### Description

This PR replaces all `SARSingleNode` with `SAR`, because `SARSingleNode` has been already imported as `SAR` in `__init__.py`:
https://github.com/microsoft/recommenders/blob/aeb6b0b12e177b3eaf55bb7ab2b747549a541394/recommenders/models/sar/__init__.py#L4

### Checklist:

- [x] I have followed the [contribution guidelines](../CONTRIBUTING.md) and code style for this project.
- [ ] I have added tests covering my contributions.
- [ ] I have updated the documentation accordingly.
- [x] This PR is being made to `staging branch` and not to `main branch`.

### CODE REVIEW

**Review by miguelgfierro — APPROVED** [review]
Agree.

Also, you migth want to delete this guy https://github.com/microsoft/recommenders/blob/main/recommenders/models/sar/__init__.py#L4

**Comment by miguelgfierro** [comment]
oh, I understood this wrong :-) I thought you were going to eliminate the name SAR single node and put SAR everywhere. 

Do you want to leave it with sar single node or you want to leave everything as SAR?

**Comment by simonzhaoms** [comment]
> oh, I understood this wrong :-) I thought you were going to eliminate the name SAR single node and put SAR everywhere.
> 
> Do you want to leave it with sar single node or you want to leave everything as SAR?

@miguelgfierro In [`recommenders/models/sar/__init__.py`](https://github.com/microsoft/recommenders/blob/main/recommenders/models/sar/__init__.py#L4), `SARSingleNode` is renamed as `SAR`, so I think all occurrences of `SARSingleNode` should be replaced with `SAR`.  Otherwise, `from .sar_singlenode import SARSingleNode as SAR` is useless, isn't it?

**Comment by miguelgfierro** [comment]
> Otherwise, from .sar_singlenode import SARSingleNode as SAR is useless, isn't it?

yes exactly, what I meant is that I thought you were planning to change all instances of `SARSingleNode` to `SAR`

**Pull request merged**
