### PR TITLE
remove early stopping round from lightgbm example notebook

### PR DESCRIPTION
**Pull request by imatiach-msft**
### Description
remove early stopping round from lightgbm example notebook since it isn't used

### Related Issues
This is a related issue to this minor notebook patch:
https://github.com/microsoft/recommenders/issues/1615

### Checklist:

- [x] I have followed the [contribution guidelines](../CONTRIBUTING.md) and code style for this project.
- [ ] I have added tests covering my contributions.
- [ ] I have updated the documentation accordingly.
- [x] This PR is being made to `staging branch` and not to `main branch`.

### CODE REVIEW

**Comment by imatiach-msft** [comment]
weird, the build seems to be failing.  did I make a mistake?

**Comment by anargyri** [comment]
> weird, the build seems to be failing. did I make a mistake?

No, this happens frequently I am afraid. The GitHub host has low resources. I will rerun the jobs.

**Review by anargyri — APPROVED** [review]

**Review by miguelgfierro — APPROVED** [review]
this is great Ilia!

**Comment by miguelgfierro** [comment]
> weird, the build seems to be failing. did I make a mistake?

it's because the default machines we have in GitHub actions have low memory. However, @pradnyeshjoshi is going to start a new set of tests using AzureML #995 that hopefully eliminated this problem and reduced massively the test time

**Comment by imatiach-msft** [comment]
thank you for merging!

**Pull request merged**
