### PR TITLE
Optimize Python splitter

### PR DESCRIPTION
**Pull request by yueguoguo**
### Description
* Optimize run-time performance of chrono splitter.
* Remove redundant codes.

### Related Issues
#462 

### Checklist:

- [x] My code follows the code style of this project, as detailed in our [contribution guidelines](../CONTRIBUTING.md).
- [x] I have added tests.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by yueguoguo** [comment]
image
@miguelgfierro 10min to split movielens10M.

**Comment by miguelgfierro** [comment]
@yueguoguo  was 10min the time before the refactoring or after? o_o

**Comment by yueguoguo** [comment]
@miguelgfierro After. In #462 you said it took 5h before...

**Comment by miguelgfierro** [comment]
Oh that's awesome!!

https://media.giphy.com/media/3oriNYQX2lC6dfW2Ji/giphy.gif

**Pull request merged**
