### PR TITLE
Wide-and-deep and Hyperdrive merging to master

### PR DESCRIPTION
**Pull request by loomlike**
### Description
Add Wide-and-deep notebook and AzureML Hyperdrive (hyperparameter tuning) notebook to Master

### Related Issues
#374, #339, #448

### Checklist:

- [x] My code follows the code style of this project, as detailed in our [contribution guidelines](../CONTRIBUTING.md).
- [x] I have added tests.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by loomlike** [comment]
**just** 41 files changed. Not bad for 'merging to master', right? ;-)
> i.e. the repo is evolving super fast! cool!!

**Comment by loomlike** [comment]
Here is the link to the milestone: https://github.com/Microsoft/Recommenders/milestone/11

**Comment by yueguoguo** [comment]
> **just** 41 files changed. Not bad for 'merging to master', right? ;-)
Just nice 👍

**Comment by miguelgfierro** [comment]
mmm, there is an error:

```
tests/smoke/test_notebooks_gpu.py ..F...                                 [100%]

=================================== FAILURES ===================================
_________________________________ test_fastai __________________________________

notebooks = {'als_deep_dive': '/data/home/recocat/cicd/18/s/notebooks/02_model/als_deep_dive.ipynb', 'als_pyspark': '/data/home/re...aseline_deep_dive.ipynb', 'data_split': '/data/home/recocat/cicd/18/s/notebooks/01_prepare_data/data_split.ipynb', ...}

    @pytest.mark.smoke
    @pytest.mark.gpu
    def test_fastai(notebooks):
        notebook_path = notebooks["fastai"]
        pm.execute_notebook(
            notebook_path,
            OUTPUT_NOTEBOOK,
            kernel_name=KERNEL_NAME,
>           parameters=dict(TOP_K=10, MOVIELENS_DATA_SIZE="100k", EPOCHS=1),
        )

tests/smoke/test_notebooks_gpu.py:73: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/anaconda/envs/nightly_reco_gpu/lib/python3.6/site-packages/papermill/execute.py:94: in execute_notebook
    raise_for_execution_errors(nb, output_path)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

nb = {'cells': [{'cell_type': 'code', 'metadata': {'inputHidden': True, 'hide_input': True}, 'execution_count': None, 'sour...nd_time': '2019-02-27T16:01:18.018787', 'duration': 13.626017, 'exception': True}}, 'nbformat': 4, 'nbformat_minor': 2}
output_path = 'output.ipynb'

    def raise_for_execution_errors(nb, output_path):
        """Assigned parameters into the appropriate place in the input notebook
    
        Parameters
        ----------
        nb : NotebookNode
           Executable notebook object
        output_path : str
           Path to write executed notebook
        """
        error = None
        for cell in nb.cells:
            if cell.get("outputs") is None:
                continue
    
            for output in cell.outputs:
                if output.output_type == "error":
                    error = PapermillExecutionError(
                        exec_count=cell.execution_count,
                        source=cell.source,
                        ename=output.ename,
                        evalue=output.evalue,
                        traceback=output.traceback,
                    )
                    break
    
        if error:
            # Write notebook back out with the Error Message at the top of the Notebook.
            error_msg = ERROR_MESSAGE_TEMPLATE % str(error.exec_count)
            error_msg_cell = nbformat.v4.new_code_cell(
                source="%%html\n" + error_msg,
                outputs=[
                    nbformat.v4.new_output(output_type="display_data", data={"text/html": error_msg})
                ],
                metadata={"inputHidden": True, "hide_input": True},
            )
            nb.cells = [error_msg_cell] + nb.cells
            write_ipynb(nb, output_path)
>           raise error
E           papermill.exceptions.PapermillExecutionError: 
E           ---------------------------------------------------------------------------
E           Exception encountered at "In [15]":
E           ---------------------------------------------------------------------------
E           AttributeError                            Traceback (most recent call last)
E           <ipython-input-15-4da50f3c3d9e> in <module>
E           ----> 1 total_users, total_items = learner.data.classes.values()
E                 2 total_items = np.array(total_items[1:])
E                 3 total_users = np.array(total_users[1:])
E           
E           /anaconda/envs/nightly_reco_gpu/lib/python3.6/site-packages/fastai/basic_data.py in __getattr__(self, k)
E               120         return cls(*dls, path=path, device=device, dl_tfms=dl_tfms, collate_fn=collate_fn, no_check=no_check)
E               121 
E           --> 122     def __getattr__(self,k:int)->Any: return getattr(self.train_dl, k)
E               123     def __setstate__(self,data:Any): self.__dict__.update(data)
E               124 
E           
E           /anaconda/envs/nightly_reco_gpu/lib/python3.6/site-packages/fastai/basic_data.py in __getattr__(self, k)
E                36 
E                37     def __len__(self)->int: return len(self.dl)
E           ---> 38     def __getattr__(self,k:str)->Any: return getattr(self.dl, k)
E                39     def __setstate__(self,data:Any): self.__dict__.update(data)
E                40 
E           
E           /anaconda/envs/nightly_reco_gpu/lib/python3.6/site-packages/fastai/basic_data.py in DataLoader___getattr__(dl, k)
E                18 torch.utils.data.DataLoader.__init__ = intercept_args
E                19 
E           ---> 20 def DataLoader___getattr__(dl, k:str)->Any: return getattr(dl.dataset, k)
E                21 DataLoader.__getattr__ = DataLoader___getattr__
E                22 
E           
E           /anaconda/envs/nightly_reco_gpu/lib/python3.6/site-packages/fastai/data_block.py in __getattr__(self, k)
E               595         res = getattr(y, k, None)
E               596         if res is not None: return res
E           --> 597         raise AttributeError(k)
E               598 
E               599     def __setstate__(self,data:Any): self.__dict__.update(data)
E           
E           AttributeError: classes

/anaconda/envs/nightly_reco_gpu/lib/python3.6/site-packages/papermill/execute.py:241: PapermillExecutionError
```
not very descriptive :-)

**Comment by miguelgfierro** [comment]
I think the error is an OOM

**Pull request merged**
