### PR TITLE
Staging to main to add latest refactoring

### PR DESCRIPTION
**Pull request by miguelgfierro**
### Checklist:

- [ ] I have followed the [contribution guidelines](../CONTRIBUTING.md) and code style for this project.
- [ ] I have added tests covering my contributions.
- [ ] I have updated the documentation accordingly.
- [ ] This PR is being made to `staging branch` and not to `main branch`.

### CODE REVIEW

**Comment by miguelgfierro** [comment]
boom

**Comment by miguelgfierro** [comment]
fixed minor issues to have all integration tests in green

**Comment by miguelgfierro** [comment]
there are several errors:

```

tests/integration/examples/test_notebooks_python.py ......F..            [ 40%]
tests/integration/reco_utils/dataset/test_criteo.py .                    [ 45%]
tests/integration/reco_utils/dataset/test_mind.py F..                    [ 59%]
tests/integration/reco_utils/dataset/test_movielens.py .........         [100%]

=================================== FAILURES ===================================
__________________________ test_wikidata_integration ___________________________

notebooks = {'als_deep_dive': '/home/recocat/myagent/_work/7/s/examples/02_model_collaborative_filtering/als_deep_dive.ipynb', 'al...p_dive': '/home/recocat/myagent/_work/7/s/examples/02_model_collaborative_filtering/cornac_bivae_deep_dive.ipynb', ...}
output_notebook = 'output.ipynb', kernel_name = 'python3'
tmp = '/tmp/pytest-of-recocat/pytest-870/tmpn7_us94g'

    @pytest.mark.integration
    def test_wikidata_integration(notebooks, output_notebook, kernel_name, tmp):
        notebook_path = notebooks["wikidata_knowledge_graph"]
        pm.execute_notebook(
            notebook_path,
            output_notebook,
            kernel_name=kernel_name,
            parameters=dict(
>               MOVIELENS_DATA_SIZE="100k", MOVIELENS_SAMPLE=True, MOVIELENS_SAMPLE_SIZE=5
            ),
        )

tests/integration/examples/test_notebooks_python.py:198: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/anaconda/envs/nightly_linux_cpu/lib/python3.6/site-packages/papermill/execute.py:122: in execute_notebook
    raise_for_execution_errors(nb, output_path)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

nb = {'cells': [{'id': '9aa6618e', 'cell_type': 'markdown', 'source': '<span style="color:red; font-family:Helvetica Neue, ...end_time': '2021-04-03T13:31:01.216649', 'duration': 7.075049, 'exception': True}}, 'nbformat': 4, 'nbformat_minor': 5}

```

FYI @anargiry @gramhagen

**Review by yueguoguo — APPROVED** [review]

**Comment by miguelgfierro** [comment]
the issue we had, fixed itself over the weekend, maybe the AI is getting recursively more intelligent?!?!?!?!?

**Pull request merged**
