### PR TITLE
Documentation of Recommenders

### PR DESCRIPTION
**Pull request by miguelgfierro**
### Description

Documentation of recommenders

I think the best way to review this is by compiling the documentation locally (see the README).

I put there the basic info. Maybe we want to add more information to the pages. Feel free to directly push to this branch if you want to add comments in any module.

### Related Issues

#817
#651

### Checklist:

- [ ] I have followed the [contribution guidelines](../CONTRIBUTING.md) and code style for this project.
- [ ] I have added tests covering my contributions.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by yueguoguo** [comment]
This is good 👍  One dummy question, in the PR how can we render it to html and view it?

**Comment by gramhagen** [comment]
> This is good 👍 One dummy question, in the PR how can we render it to html and view it?

instructions in readme: https://github.com/microsoft/recommenders/blob/documentation/docs/README.md

**Comment by yueguoguo** [comment]
Just noticed that - thanks @gramhagen for pointing it out!

**Comment by miguelgfierro** [comment]
I ended up hosting the documentation in prometheus http://prometheus.europe.corp.microsoft.com/recommenders, in case anyone wants to take a look, this is probably quicker

**Comment by yueguoguo** [comment]
@miguelgfierro I still have issue accessing the site, even in the corp net...

**Comment by miguelgfierro** [comment]
can you try again now?

**Comment by miguelgfierro** [comment]
there is this error:
```
https://msdata.visualstudio.com/AlgorithmsAndDataScience/_build/results?buildId=3958431&view=logs&jobId=fd490c07-0b22-5182-fac9-6d67fe1e939b&taskId=00933dce-c782-5c03-4a85-76379ccfa50a&lineStart=23&lineEnd=51&colStart=1&colEnd=54
```

not sure whether it is something that I touch ...

**Pull request merged**
