### PR TITLE
Prepare for new release

### PR DESCRIPTION
**Pull request by miguelgfierro**
### Checklist:

- [ ] I have followed the [contribution guidelines](../CONTRIBUTING.md) and code style for this project.
- [ ] I have added tests covering my contributions.
- [ ] I have updated the documentation accordingly.
- [ ] This PR is being made to `staging branch` and not to `main branch`.

### CODE REVIEW

**Comment by pradnyeshjoshi** [comment]
> @pradnyeshjoshi we have an issue with the spark tuning code, I don't think it is a problem with this particular PR, but it is annoying

@miguelgfierro this is weird, I just merged #1763, did not get this error there.

**Comment by miguelgfierro** [comment]
> @miguelgfierro this is weird, I just merged https://github.com/microsoft/recommenders/pull/1763, did not get this error there.

yeah, I think that precise test is flaky. I have reexecuted the failed jobs

**Comment by miguelgfierro** [comment]
@pradnyeshjoshi @anargyri this is annoying, the test failed again. This spark tunning is super flaky:
```
============================= slowest 10 durations =============================
250.20s call     tests/unit/examples/test_notebooks_pyspark.py::test_spark_tuning
225.70s call     tests/unit/examples/test_notebooks_pyspark.py::test_spark_tuning
203.54s call     tests/unit/examples/test_notebooks_pyspark.py::test_spark_tuning
175.64s call     tests/unit/examples/test_notebooks_pyspark.py::test_spark_tuning
166.25s call     tests/unit/examples/test_notebooks_pyspark.py::test_spark_tuning
139.28s call     tests/unit/examples/test_notebooks_pyspark.py::test_spark_tuning
(4 durations < 0.005s hidden.  Use -vv to show these durations.)
=========================== short test summary info ============================
FAILED tests/unit/examples/test_notebooks_pyspark.py::test_spark_tuning - pap...
```

**Comment by anargyri** [comment]
Yes, this is difficult to understand. One thing that is special with this test in particular is that we call `ALS.fit()` two or three times. So, I would speculate that this may "overload" the resources allocated by Spark in some way. I suggest you try separating the ALS training runs into separate tests and see if this fixes the issue. It's probably feasible to do this by parameterizing the notebook in a creative way.

**Comment by miguelgfierro** [comment]
Added issue about this: https://github.com/microsoft/recommenders/issues/1770

**Comment by miguelgfierro** [comment]
@pradnyeshjoshi I have merged staging with your latest changes, hopefully we don't see the error in the tests anymore. Please review this PR

**Comment by pradnyeshjoshi** [comment]
> @pradnyeshjoshi I have merged staging with your latest changes, hopefully we don't see the error in the tests anymore. Please review this PR

@miguelgfierro I cannot review this PR, it says I need to be a code owner to review,

**Review by pradnyeshjoshi — APPROVED** [review]

**Pull request merged**
