### PR TITLE
Added jobs into yaml tests

### PR DESCRIPTION
**Pull request by miguelgfierro**
### Description

Added jobs in the yaml files

Also fixed a bug in the test pipeline of gpu https://dev.azure.com/best-practices/recommenders/_build/results?buildId=14699 due to a wrong placement of the time out input

Also added `durations 0` to list computation times for the tests

### Checklist:

- [ ] I have followed the [contribution guidelines](../CONTRIBUTING.md) and code style for this project.
- [ ] I have added tests covering my contributions.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by miguelgfierro** [comment]
this is the error I'm getting:
```
/tests/ci/azure_pipeline_test/dsvm_unit_win_cpu.yml: (Line: 27, Col: 5, Idx: 539) - (Line: 27, Col: 5, Idx: 539): While scanning a simple key, could not find expected ':'.
```
I need to investigage

**Comment by yueguoguo** [comment]
Was there the same error before change? @miguelgfierro

**Comment by miguelgfierro** [comment]
the env might not be installed correctly, there error is:
```
[command]/bin/bash --noprofile --norc /data/home/recocat/agent/_work/_temp/eeef47ef-e675-4509-b0c2-f0eb93808f38.sh
Could not find conda environment: reco_gpu
You can list all discoverable environments with `conda info --envs`.
```

**Comment by miguelgfierro** [comment]
added the conda env to the machine

**Comment by yueguoguo** [comment]
LGTM! Thanks @miguelgfierro

**Pull request merged**
