### PR TITLE
Fixed SAR notebooks

### PR DESCRIPTION
**Pull request by ChuyangKe**
### Description
Fixed the error that in SAR notebooks, the TOP_K parameter is not properly supplied to function model.recommend_k_items().

### Checklist:

- [x] I have followed the [contribution guidelines](../CONTRIBUTING.md) and code style for this project.
- [ ] I have added tests covering my contributions.
- [x] I have updated the documentation accordingly.
- [x] This PR is being made to `staging branch` and not to `main branch`.

### CODE REVIEW

**Review by gramhagen — APPROVED** [review]
looks good, thanks!

**Review by anargyri — APPROVED** [review]

**Review by miguelgfierro — APPROVED** [review]
@ChuyangKe congrats for your first PR! Awesome!

**Comment by miguelgfierro** [comment]
@pradnyeshjoshi this PR has an error with the AzureML credentials, however, this one doesn't have any error: https://github.com/microsoft/recommenders/pull/1739 Do you know what could be happening?

**Comment by pradnyeshjoshi** [comment]
> @pradnyeshjoshi this PR has an error with the AzureML credentials, same as #1736, however, this one doesn't have any error: #1739 Do you know what could be happening?

@miguelgfierro Looks like @ChuyangKe has created a fork of the repo, and GitHub Actions has no way to make secrets available to forks, so it's not able to find the login credentials - this is my guess.

**Comment by ChuyangKe** [comment]
> k of the repo, and GitHub Actions has no way to make secrets available to forks, so it's not able to find the login credentials.

@pradnyeshjoshi Yes I created a fork to my account. Do I need to push in other ways?

**Comment by pradnyeshjoshi** [comment]
> > k of the repo, and GitHub Actions has no way to make secrets available to forks, so it's not able to find the login credentials.
> 
> @pradnyeshjoshi Yes I created a fork to my account. Do I need to push in other ways?

@ChuyangKe we usually create a feature branch off of staging in the same repo and create a pull request into staging. AzureML tests in this PR are failing because the credentials to log into AzureML (as part of unit test workflow) are stored as repo level secrets. I am looking into how we can support PRs from forks.

**Comment by miguelgfierro** [comment]
@pradnyeshjoshi the same thing is failing here: https://github.com/microsoft/recommenders/pull/1732 are you sure it is related to the fork?

**Comment by miguelgfierro** [comment]
I'm rerunning again all the tests FYI @pradnyeshjoshi @ChuyangKe

**Comment by miguelgfierro** [comment]
same error @chuyangke, can you merge the latest staging into your branch sar_fix? and then push again? this should fix the problem and trigger the tests

**Comment by miguelgfierro** [comment]
I will merge this because I think with the new PR of @pradnyeshjoshi  solved the AzureML issue

**Pull request merged**
