### PR TITLE
Staging to master due to milestone 14 finished Hyperparameter tuning on AzureML

### PR DESCRIPTION
**Pull request by miguelgfierro**
### Related Issues

https://github.com/Microsoft/Recommenders/milestone/14

### Checklist:

- [x] My code follows the code style of this project, as detailed in our [contribution guidelines](../CONTRIBUTING.md).
- [x] I have added tests.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by yueguoguo** [comment]
Kudos to all the code contributors!

**Comment by anargyri** [comment]
In the README, it is not accurate that model selection notebooks require AzureML (two of them do, one does not)

**Comment by miguelgfierro** [comment]
good catch @anargyri, do you want to make the change? if you are busy I can do it

**Comment by anargyri** [comment]
> good catch @anargyri, do you want to make the change? if you are busy I can do it

I can do it.

**Pull request merged**
