### PR TITLE
Set up CI with Azure Pipelines

### PR DESCRIPTION
**Pull request by bethz**

### CODE REVIEW

**Comment by gramhagen** [comment]
@bethz, for PRs we merge them to staging first then after all the items in a milestone have been pulled into staging we'll do a release to master. See the wiki for a little more detail: https://github.com/Microsoft/Recommenders/wiki/Strategy-to-merge-the-code-to-master-branch

In terms of what you're working on here, do you need to push this first step into staging? Or is it possible to continue to work on it in a separate branch without requiring PR?

**Comment by yueguoguo** [comment]
I changed the target branch to `staging`. 

May I know more context about this PR? It is not easy to tell directly from the commits. Also, it would be great if a detailed description of the PR can be provided. We have made a template for that and by default it appears when you create a new PR. The description will help reviewers understand the context, content, and other necessary information before performing a quality review. The PR #534 created by @gramhagen may be a good example.

**Comment by bethz** [comment]
I set up a public pipeline in Azure DevOps and when pointed to Recommenders it automatically created this PR (without saying it did that).  I'll add more detail and look at Scott's references. I appreciate the pointers! thanks.

**Comment by bethz** [comment]
I'm going to close this PR as I was assigned this as an issue:
https://github.com/Microsoft/Recommenders/issues/425

**Pull request closed without merging**
