### PR TITLE
Staging to main (SARplus, SASrec, NCF, RBM etc.)

### PR DESCRIPTION
**Pull request by anargyri**
### Description

Merge recent changes into main.

### Checklist:

- [x] I have followed the [contribution guidelines](../CONTRIBUTING.md) and code style for this project.
- [x] I have added tests covering my contributions.
- [x] I have updated the documentation accordingly.
- [ ] This PR is being made to `staging branch` and not to `main branch`.

### CODE REVIEW

**Review by miguelgfierro — APPROVED** [review]
Vamos!!!

**Comment by anargyri** [comment]
There was a timeout, the test pipeline takes more than 6 hours now.
See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes

**Comment by anargyri** [comment]
> There was a timeout, the test pipeline takes more than 6 hours now. See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes

See #1661

**Comment by miguelgfierro** [comment]
We still have this problem with the coverage, @laserprec is there any way to quickly fix it?

**Comment by miguelgfierro** [comment]
@anargyri weird error in the GPU nightly build: https://dev.azure.com/best-practices/recommenders/_build/results?buildId=58051&view=logs&j=11a98e2c-5412-5289-91fd-519c9484010b I'll take a look at this one

**Comment by anargyri** [comment]
> @anargyri weird error in the GPU nightly build: https://dev.azure.com/best-practices/recommenders/_build/results?buildId=58051&view=logs&j=11a98e2c-5412-5289-91fd-519c9484010b I'll take a look at this one

Now, everything passes.

**Comment by miguelgfierro** [comment]
> @anargyri weird error in the GPU nightly build: https://dev.azure.com/best-practices/recommenders/_build/results?buildId=58051&view=logs&j=11a98e2c-5412-5289-91fd-519c9484010b I'll take a look at this one

not sure what happened, I triggered again and it worked. I'll wait to see if this is an error with the scheduler

**Comment by anargyri** [comment]
> > @anargyri weird error in the GPU nightly build: https://dev.azure.com/best-practices/recommenders/_build/results?buildId=58051&view=logs&j=11a98e2c-5412-5289-91fd-519c9484010b I'll take a look at this one
> 
> not sure what happened, I triggered again and it worked. I'll wait to see if this is an error with the scheduler

Strange. I also see this
```
$ nvidia-smi
Failed to initialize NVML: Driver/library version mismatch
```
However TensorFlow can see the GPU. I will reboot the machine when no tests are running.

**Comment by anargyri** [comment]
So there is one Spark test failing but it is likely due to the GitHub host. I tried the test on a Standard NC6 and it passed successfully.

**Comment by anargyri** [comment]
There is a failing test on ADO (tests/unit/examples/test_notebooks_gpu.py::test_ncf_deep_dive) but the strange thing is that it works on its own and fails when run with `-m "notebooks and not spark and gpu"`.

**Comment by miguelgfierro** [comment]
@anargyri are we all green?

**Comment by anargyri** [comment]
> @anargyri are we all green?

Not yet. GPU integration tests timed out after 7 hours (!) yesterday, let's hope today they are faster.

**Comment by anargyri** [comment]
> > @anargyri are we all green?
> 
> Not yet. GPU integration tests timed out after 7 hours (!) yesterday, let's hope today they are faster.

Phew, it took 6hrs 48 mins 😃 
We are all green now!

**Comment by miguelgfierro** [comment]
The GPU integration tests on GitHub takes ~7h https://github.com/microsoft/recommenders/runs/5549806940?check_suite_focus=true, however, the smoke+integration in ADO takes ~4h https://dev.azure.com/best-practices/recommenders/_build?definitionId=163 the only difference is the machine?

**Comment by anargyri** [comment]
> The GPU integration tests on GitHub takes ~7h https://github.com/microsoft/recommenders/runs/5549806940?check_suite_focus=true, however, the smoke+integration in ADO takes ~4h https://dev.azure.com/best-practices/recommenders/_build?definitionId=163 the only difference is the machine?

There are a few differences, whether relevant or not:
- AzureML VM Standard_NC6 (6 cores, 56 GB RAM, 380 GB disk, Tesla K80 with 12GB memory) vs. DSVM Standard NC6s v2 (6 vcpus, 112 GiB memory, Tesla P100 with 16GB memory)
- Python 3.7 vs. 3.6 which also implies TensorFlow 2.7 vs. 2.6
- tox vs. conda

Most likely the better GPU makes a lot of difference 😆

**Pull request merged**
