### PR TITLE
Staging to master to fix bugs in tests

### PR DESCRIPTION
**Pull request by miguelgfierro**
### Checklist:

- [ ] I have followed the [contribution guidelines](../CONTRIBUTING.md) and code style for this project.
- [ ] I have added tests covering my contributions.
- [ ] I have updated the documentation accordingly.
- [ ] This PR is being made to `staging` and not `master`.

### CODE REVIEW

**Comment by yueguoguo** [comment]
What is the `packaging_tutorial-CI`?

**Comment by miguelgfierro** [comment]
> What is the packaging_tutorial-CI?

@vapaunic do you know what is this? it links to https://vapaunic.visualstudio.com/154797b3-2afd-4ae1-87a4-bd7f650f039f/_build/results?buildId=18 but I can't access it

**Comment by vapaunic** [comment]
@miguelgfierro , this is a pipeline I built in my private devops account to package Recommenders and push it to Artifacts (just to try out what we were talking about). Didn't realize it was going to show up here, weird! I deleted the pipeline since. Could you push another commit, and see if it gets triggered again? It shouldn't.

**Comment by miguelgfierro** [comment]
ok thanks no problem, I think we can ignore it

**Pull request merged**
