### PR TITLE
Miguel/mrsa seq readme

### PR DESCRIPTION
**Pull request by miguelgfierro**
### Description

Updated readme for Jianxun notebooks

### Checklist:

- [ ] I have followed the [contribution guidelines](../CONTRIBUTING.md) and code style for this project.
- [ ] I have added tests covering my contributions.
- [ ] I have updated the documentation accordingly.
- [ ] This PR is being made to `staging` and not `master`.

### CODE REVIEW

**Comment by loomlike** [comment]
I just realized that we link corresponding notebooks of each algo under the environment column of the table.

So, one should click, e.g.
|...|environment|
|---|---|
|...|Python CPU / Python GPU|

 to open the notebook. Is this straightforward?

**Comment by miguelgfierro** [comment]
>  Is this straightforward?

Yeah I agree this is not very straightforward. Let me propose here several alternatives to see how they will look like:

Alternative 1:

| Algorithm | Environment | Type | Description |
| --- | --- | --- | --- |
| Alternating Least Squares (ALS) ([pyspark notebook](notebooks/00_quick_start/als_movielens.ipynb)) | PySpark | Collaborative Filtering | Matrix factorization algorithm for explicit or implicit feedback in large datasets, optimized by Spark MLLib for scalability and distributed computing capability |
| Cornac/Bayesian Personalized Ranking (BPR) ([cpu notebook](notebooks/02_model/cornac_bpr_deep_dive.ipynb)) | Python CPU | Collaborative Filtering | Matrix factorization algorithm for predicting item ranking with implicit feedback |
| Deep Knowledge-Aware Network (DKN)<sup>*</sup> ([gpu notebook](notebooks/00_quick_start/dkn_synthetic.ipynb)) | Python CPU / Python GPU | Content-Based Filtering | Deep learning algorithm incorporating a knowledge graph and article embeddings to provide powerful news or article recommendations |
| LightGBM/Gradient Boosting Tree<sup>*</sup> ([cpu notebook](notebooks/00_quick_start/lightgbm_tinycriteo.ipynb) / [spark notebook](notebooks/02_model/mmlspark_lightgbm_criteo.ipynb)) | Python CPU / PySpark| Content-Based Filtering | Gradient Boosting Tree algorithm for fast training and low memory usage in content-based problems |

Alternative 2:

| Algorithm | Environment | Type | Description |
| --- | --- | --- | --- |
| Alternating Least Squares (ALS) ([pyspark notebook](notebooks/00_quick_start/als_movielens.ipynb)) | reco_pyspark | Collaborative Filtering | Matrix factorization algorithm for explicit or implicit feedback in large datasets, optimized by Spark MLLib for scalability and distributed computing capability |
| Cornac/Bayesian Personalized Ranking (BPR) ([cpu notebook](notebooks/02_model/cornac_bpr_deep_dive.ipynb)) | reco_base | Collaborative Filtering | Matrix factorization algorithm for predicting item ranking with implicit feedback |
| Deep Knowledge-Aware Network (DKN)<sup>*</sup> ([gpu notebook](notebooks/00_quick_start/dkn_synthetic.ipynb)) | reco_base/reco_gpu | Content-Based Filtering | Deep learning algorithm incorporating a knowledge graph and article embeddings to provide powerful news or article recommendations |
| LightGBM/Gradient Boosting Tree<sup>*</sup> ([cpu notebook](notebooks/00_quick_start/lightgbm_tinycriteo.ipynb) / [spark notebook](notebooks/02_model/mmlspark_lightgbm_criteo.ipynb)) | reco_base /reco_pyspark| Content-Based Filtering | Gradient Boosting Tree algorithm for fast training and low memory usage in content-based problems |


Alternative 3:

| Algorithm | Environment | Type | Description |
| --- | --- | --- | --- |
| Alternating Least Squares (ALS) ([pyspark notebook](notebooks/00_quick_start/als_movielens.ipynb)) | Spark | Collaborative Filtering | Matrix factorization algorithm for explicit or implicit feedback in large datasets, optimized by Spark MLLib for scalability and distributed computing capability |
| Cornac/Bayesian Personalized Ranking (BPR) ([cpu notebook](notebooks/02_model/cornac_bpr_deep_dive.ipynb)) | CPU | Collaborative Filtering | Matrix factorization algorithm for predicting item ranking with implicit feedback |
| Deep Knowledge-Aware Network (DKN)<sup>*</sup> ([gpu notebook](notebooks/00_quick_start/dkn_synthetic.ipynb)) | CPU/GPU | Content-Based Filtering | Deep learning algorithm incorporating a knowledge graph and article embeddings to provide powerful news or article recommendations |
| LightGBM/Gradient Boosting Tree<sup>*</sup> ([cpu notebook](notebooks/00_quick_start/lightgbm_tinycriteo.ipynb) / [spark notebook](notebooks/02_model/mmlspark_lightgbm_criteo.ipynb)) | CPU/Spark  | Content-Based Filtering | Gradient Boosting Tree algorithm for fast training and low memory usage in content-based problems |

Alternative 4:

| Algorithm | Environment | Implementation| Type | Description |
| --- | --- | --- | --- | --- |
| Alternating Least Squares (ALS) | Spark |  [pyspark notebook](notebooks/00_quick_start/als_movielens.ipynb) | Collaborative Filtering | Matrix factorization algorithm for explicit or implicit feedback in large datasets, optimized by Spark MLLib for scalability and distributed computing capability |
| Cornac/Bayesian Personalized Ranking (BPR) | CPU | [cpu notebook](notebooks/02_model/cornac_bpr_deep_dive.ipynb) | Collaborative Filtering | Matrix factorization algorithm for predicting item ranking with implicit feedback |
| Deep Knowledge-Aware Network (DKN)<sup>*</sup> | CPU/GPU | [gpu notebook](notebooks/00_quick_start/dkn_synthetic.ipynb) | Content-Based Filtering | Deep learning algorithm incorporating a knowledge graph and article embeddings to provide powerful news or article recommendations |
| LightGBM/Gradient Boosting Tree<sup>*</sup> | CPU/Spark | [cpu notebook](notebooks/00_quick_start/lightgbm_tinycriteo.ipynb) / [spark notebook](notebooks/02_model/mmlspark_lightgbm_criteo.ipynb) | Content-Based Filtering | Gradient Boosting Tree algorithm for fast training and low memory usage in content-based problems |


Alternative 5:

| Algorithm | Environment | Implementation| Type | Scenario | Description |
| --- | --- | --- | --- | --- | --- |
| Alternating Least Squares (ALS) | Spark |  [pyspark notebook](notebooks/00_quick_start/als_movielens.ipynb) | Collaborative Filtering | General recommendations | Matrix factorization algorithm for explicit or implicit feedback in large datasets, optimized by Spark MLLib for scalability and distributed computing capability |
| Cornac/Bayesian Personalized Ranking (BPR) | CPU | [cpu notebook](notebooks/02_model/cornac_bpr_deep_dive.ipynb) | Collaborative Filtering | General recommendations | Matrix factorization algorithm for predicting item ranking with implicit feedback |
| Deep Knowledge-Aware Network (DKN)<sup>*</sup> | CPU/GPU | [gpu notebook](notebooks/00_quick_start/dkn_synthetic.ipynb) | Content-Based Filtering | news recommendations/Knowledge graph recommendations | Deep learning algorithm incorporating a knowledge graph and article embeddings to provide powerful news or article recommendations |
| LightGBM/Gradient Boosting Tree<sup>*</sup> | CPU/Spark | [cpu notebook](notebooks/00_quick_start/lightgbm_tinycriteo.ipynb) / [spark notebook](notebooks/02_model/mmlspark_lightgbm_criteo.ipynb) | Content-Based Filtering | Content recommendation | Gradient Boosting Tree algorithm for fast training and low memory usage in content-based problems |

Alternative 6:

| Algorithm | Implementation| Scenario | Description |
| --- | --- | --- | --- | 
| Alternating Least Squares (ALS) | [pyspark notebook](notebooks/00_quick_start/als_movielens.ipynb) | Collaborative Filtering for general recommendations | Matrix factorization algorithm for explicit or implicit feedback in large datasets, optimized by Spark MLLib for scalability and distributed computing capability |
| Cornac/Bayesian Personalized Ranking (BPR) | [cpu notebook](notebooks/02_model/cornac_bpr_deep_dive.ipynb) | Collaborative Filtering for general recommendations | Matrix factorization algorithm for predicting item ranking with implicit feedback |
| Deep Knowledge-Aware Network (DKN)<sup>*</sup> | [gpu notebook](notebooks/00_quick_start/dkn_synthetic.ipynb) | Content-Based Filtering for news recommendations/Knowledge graph recommendations | Deep learning algorithm incorporating a knowledge graph and article embeddings to provide powerful news or article recommendations |
| LightGBM/Gradient Boosting Tree<sup>*</sup> | [cpu notebook](notebooks/00_quick_start/lightgbm_tinycriteo.ipynb) / [spark notebook](notebooks/02_model/mmlspark_lightgbm_criteo.ipynb) | Content-Based Filtering for content recommendation | Gradient Boosting Tree algorithm for fast training and low memory usage in content-based problems |

**Comment by loomlike** [comment]
I like the option 6! Not too many columns, the column name 'Implementation' totally make sense (because the implementation of those algos we use are for cpu / gpu / spark, not the algorithms' requirement). 'Scenario' appeals more to non-experts who are not necessarily know which type of algo they will need.

What's others thought?

**Comment by anargyri** [comment]
> I like the option 6! Not too many columns, the column name 'Implementation' totally make sense (because the implementation of those algos we use are for cpu / gpu / spark, not the algorithms' requirement). 'Scenario' appeals more to non-experts who are not necessarily know which type of algo they will need.
> 
> What's others thought?

+1 for option 6. I would not mind option 1 either. Also, I tend to prefer "PySpark" vs. "Spark" and "Python CPU" vs. "CPU", it is a bit more informative.

**Comment by wutaomsft** [comment]
if option 6, would it be good to have order of columns to be scenario-algo-description-env?

**Comment by miguelgfierro** [comment]
@wutaomsft added alternative 7 (I need to work in the format a little) but I hope I'm reflecting the idea you proposed

**Comment by anargyri** [comment]
> @wutaomsft added alternative 7 (I need to work in the format a little) but I hope I'm reflecting the idea you proposed

I like 7, especially that one scenario can map to many algorithms.

**Comment by yueguoguo** [comment]
+1 to alternative 7

**Comment by miguelgfierro** [comment]
close this PR and merge it in #1099

**Pull request closed without merging**
