### PR TITLE
Release 1.0.0

### PR DESCRIPTION
**Pull request by anargyri**
### Description

- Migration to Spark 3
- Migration to TensorFlow 2
- Migration of SARplus to Spark 3
- Other changes and fixes for release 1.0.0

### Checklist:

- [x] I have followed the [contribution guidelines](../CONTRIBUTING.md) and code style for this project.
- [x] I have added tests covering my contributions.
- [x] I have updated the documentation accordingly.
- [ ] This PR is being made to `staging branch` and not to `main branch`.

### CODE REVIEW

**Comment by anargyri** [comment]
@simonzhaoms any idea about the failing sarplus test?

**Comment by miguelgfierro** [comment]
@anargyri do you want to add the changes in the main README that you had in your branch announcing the release?

**Comment by anargyri** [comment]
> @anargyri do you want to add the changes in the main README that you had in your branch announcing the release?

See https://github.com/microsoft/recommenders/pull/1584

**Comment by anargyri** [comment]
> > @anargyri do you want to add the changes in the main README that you had in your branch announcing the release?
> 
> See #1584

Just merged the changes.

**Review by miguelgfierro — APPROVED** [review]
Looks good to me.
It would be good to check whether the ADO tests are all passing, with this error we have on GitHub, they are not seen in the PR page, we need to go to ADO

**Comment by anargyri** [comment]
I think there was a problem and the GPU was not visible any more. I restarted the VM and am rerunning the NAML test.

**Comment by anargyri** [comment]
> I think there was a problem and the GPU was not visible any more. I restarted the VM and am rerunning the NAML test.

Ok, the NAML test passed on the VM. Should we merge into main?

**Pull request merged**
