### PR TITLE
Create pypi-publish-action.yml

### PR DESCRIPTION
**Pull request by dciborow**
### Checklist:

- [x] I have followed the [contribution guidelines](../CONTRIBUTING.md) and code style for this project.
- [ ] I have added tests covering my contributions.
- [x] I have updated the documentation accordingly.
- [ ] This PR is being made to `staging branch` and not to `main branch`.

### CODE REVIEW

**Comment by anargyri** [comment]
Could you move this from main to staging?

**Comment by miguelgfierro** [comment]
> Could you move this from main to staging?

@anargyri since there is only one new file, if we just change it in the dashboard, I think we shouldn't get a lot of errors. I can help if you want

**Comment by anargyri** [comment]
> > Could you move this from main to staging?
> 
> @anargyri since there is only one new file, if we just change it in the dashboard, I think we shouldn't get a lot of errors. I can help if you want

So if we merge it to main this action will be active, right? This needs to be the last change we do after we have finalized everything else (package name, setup.py etc.). I'd also rather test things with manual publishing before we automate. I suggest we keep it open until we have the rest in place.

**Comment by miguelgfierro** [comment]
@dciborow this PR is the same thing as https://github.com/microsoft/recommenders/pull/1481?

**Comment by laserprec** [comment]
Should we close this PR since it looks like a duplicate of  #1481?

**Pull request closed without merging**
