### PR TITLE
Unit test for spark hypertune notebook

### PR DESCRIPTION
**Pull request by yueguoguo**
### Description
Unit test for the Spark hypertune notebook.

### Related Issues
#542 

### Checklist:

- [ ] My code follows the code style of this project, as detailed in our [contribution guidelines](../CONTRIBUTING.md).
- [x] I have added tests.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by yueguoguo** [comment]
@miguelgfierro @anargyri this test takes some time and it resulted in time-out failure.

**Comment by miguelgfierro** [comment]
I see, what we have done in the past is either to move this to smoke/integration test or to add parameters in the unit tests so it makes as less loops as possible

**Comment by yueguoguo** [comment]
> I see, what we have done in the past is either to move this to smoke/integration test or to add parameters in the unit tests so it makes as less loops as possible

But this is not a smoke/integration test - it is just to run the notebook and check if there is any failure, like other unit tests for notebooks. The only thing is that the notebook itself takes some time to finish...

**Comment by miguelgfierro** [comment]
yeah, that's right, then maybe we can parametrize it and reduce the number of runs. Do you know how long does it take to run this notebook with the current parameters?

**Comment by yueguoguo** [comment]
> yeah, that's right, then maybe we can parametrize it and reduce the number of runs. Do you know how long does it take to run this notebook with the current parameters?

~30 - 40 min

**Comment by miguelgfierro** [comment]
oh that's a lot for a unit test

**Comment by yueguoguo** [comment]
@miguelgfierro parameterize the notebook and it now takes 3~4 mins 🚀

**Pull request merged**
