### PR TITLE
update sequential reco models: add serving example

### PR DESCRIPTION
**Pull request by Leavingseason**
### Description

Update deeprec's sequential recommender packages. Provide an example for users how can we use the trained model for serving purpose.

### Related Issues

https://github.com/microsoft/recommenders/issues/1233 
https://github.com/microsoft/recommenders/issues/1068

### Checklist:

- [x] I have followed the [contribution guidelines](../CONTRIBUTING.md) and code style for this project.
- [ ] I have added tests covering my contributions.
- [x] I have updated the documentation accordingly.
- [x] This PR is being made to `staging` and not `master`.

### CODE REVIEW

**Comment by miguelgfierro** [comment]
hey @leavingseason this is awesome, but the notebook is not loading for me, I think it might be because it has too many logs. 

Do you think we can clean or reduce the output of the cell:

```
G = tf.Graph()
with tf.gfile.GFile(
        os.path.join(hparams.MODEL_DIR, "serving_model.pb"),
        'rb'
) as f, G.as_default():
    graph_def_optimized = tf.GraphDef()
    graph_def_optimized.ParseFromString(f.read())
    print('graph_def_optimized = ' + str(graph_def_optimized))


with tf.Session(graph=G) as sess:
    tf.import_graph_def(graph_def_optimized)

    model = LoadFrozedPredModel(sess.graph)
    
    serving_output_file = os.path.join(data_path, r'output_serving.txt')  
    iterator = input_creator(hparams, tf.Graph())
    infer_as_serving(model, test_file, serving_output_file, hparams, iterator, sess)

```

**Comment by Leavingseason** [comment]
> hey @Leavingseason this is awesome, but the notebook is not loading for me, I think it might be because it has too many logs.
> 
> Do you think we can clean or reduce the output of the cell:
> 
> ```
> G = tf.Graph()
> with tf.gfile.GFile(
>         os.path.join(hparams.MODEL_DIR, "serving_model.pb"),
>         'rb'
> ) as f, G.as_default():
>     graph_def_optimized = tf.GraphDef()
>     graph_def_optimized.ParseFromString(f.read())
>     print('graph_def_optimized = ' + str(graph_def_optimized))
> 
> 
> with tf.Session(graph=G) as sess:
>     tf.import_graph_def(graph_def_optimized)
> 
>     model = LoadFrozedPredModel(sess.graph)
>     
>     serving_output_file = os.path.join(data_path, r'output_serving.txt')  
>     iterator = input_creator(hparams, tf.Graph())
>     infer_as_serving(model, test_file, serving_output_file, hparams, iterator, sess)
> ```

Sure. I have removed the printing of graph content

**Review by miguelgfierro — APPROVED** [review]
Awesome!

**Comment by aidenpearce001** [comment]
Why i get error AssertionError: pred is not in graph, when running this code
soemthing

**Comment by Leavingseason** [comment]
@aidenpearce001  are you using the latest code?  In this PR, I update the base model with one line of code "pred = tf.identity(pred, name='pred')"

**Comment by aidenpearce001** [comment]
> @aidenpearce001 are you using the latest code? In this PR, I update the base model with one line of code "pred = tf.identity(pred, name='pred')"

Thanks you for helping me. I want to ask about model output when using model.predict(), its just return a number but i want it to return probability for each items so i can recommend a list of item for user. How can i do it?

**Comment by Leavingseason** [comment]
Each line is an instance of <user, item> pair. So enumerate all the items you need to make prediction for the user. E.g., if you have 100 items to rate, you need to generate 100 lines of <user, item> pairs.  SLi-Rec model is for ranking purpose, not suitable for item retrieval.

**Pull request merged**
