### PR TITLE
O16n notebook update 

### PR DESCRIPTION
**Pull request by loomlike**
O16n (ALS) notebook update 

### Description
This changes includes:
* Revise databricks setup to zip only necessary codes (`./reco_utils`)
* Change cosmosdb writing codes for better performance (previously, took more than 10 minutes to write into the db. Now it takes 3-5 secs. It is a known [issue](https://github.com/Azure/azure-cosmosdb-spark/issues/318)).
* Cleanup unused imports
* Re-format the notebook cells

### Checklist:

- [x] I have followed the [contribution guidelines](../CONTRIBUTING.md) and code style for this project.
- [ ] I have added tests covering my contributions.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by miguelgfierro** [comment]
is there a relationship between this PR and what we have been doing in the branch ignite?

**Comment by loomlike** [comment]
@miguelgfierro Yes and no... 
* yes part:
   - found cosmosDB writing issue while working on `ignite` branch, so fix that here
   - used more explicit try / except in `ignite` branch, so applied them to here
* no part:
   - `ignite` branch uses notebook vm. This notebook assumes to be run on Databricks
   - `ignite` branch uses AzureML api for setup image environment. I haven't touched that part in this notebook (this notebook uses "written env file")

**Comment by miguelgfierro** [comment]
I have been looking at both notebooks, the one you changed https://github.com/microsoft/recommenders/blob/765f51ee75b37e183817472534d53fa543c0ef90/notebooks/05_operationalize/als_movie_o16n.ipynb and the one that we have in ignite branch https://github.com/microsoft/recommenders/blob/ignite/notebooks/05_operationalize/als_movie_o16n.ipynb with the contributions of @Chris113113 and a modification I made https://github.com/microsoft/recommenders/blob/61728d869caef8c2a9b1cdbad1fec3e30b2e81cb/notebooks/05_operationalize/als_movie_o16n.ipynb that should run in DB and in a notebook.

The content is maybe 95% the same. I think we should have all together. If we use the branch ignite we just need to revert the hardcoded variables and leave it like this notebook and then add again the `if not is_jupyter:` couple of instances that we originally have.

Does this make sense?

**Comment by loomlike** [comment]
@miguelgfierro I like the idea of using `is_jupyter`. The only thing we have to deal with is the beginning section's explanation and diagram about Databricks. Do we want to change that to be more general term, like "remote compute" or something like that?

**Comment by miguelgfierro** [comment]
> @miguelgfierro I like the idea of using is_jupyter. The only thing we have to deal with is the beginning section's explanation and diagram about Databricks. Do we want to change that to be more general term, like "remote compute" or something like that?

yeah that's a good point. I think remote compute or compute target or whatever, and then explain that this notebook has been tested on Databricks and on AzureML Notebook VM

**Comment by loomlike** [comment]
@miguelgfierro I will make another commit to this PR to merge ignite branch together.

**Comment by loomlike** [comment]
I'm closing this PR for #1003 as promised

**Pull request closed without merging**
