### PR TITLE
Rewrote get_top_k_items() to improve runtime

### PR DESCRIPTION
**Pull request by ChuyangKe**
### Description

Rewrote get_top_k_items().

Optimize the runtime of ranking metrics.

### Checklist:

- [x] I have followed the [contribution guidelines](../CONTRIBUTING.md) and code style for this project.
- [ ] I have added tests covering my contributions.
- [x] I have updated the documentation accordingly.
- [x] This PR is being made to `staging branch` and not to `main branch`.

### CODE REVIEW

**Comment by gramhagen** [comment]
Do you have any timing results on this change?

**Comment by ChuyangKe** [comment]
> Do you have any timing results on this change?

I tested the old vs new function on the movielens dataset with 1m samples. I set k = 10. 

Here are the results:
original_time: 5.363674836989958 seconds.
new_time: 0.12664664999465458 seconds.

**Review by simonzhaoms — APPROVED** [review]

**Comment by simonzhaoms** [comment]
@ChuyangKe Could you please also add a test case for `get_top_k_items()` in [`tests/unit/recommenders/evaluation/test_python_evaluation.py`](https://github.com/microsoft/recommenders/blob/main/tests/unit/recommenders/evaluation/test_python_evaluation.py)?  I find there is no test for `get_top_k_items()`.  I think you can use the data from [`rating_true`](https://github.com/microsoft/recommenders/blob/main/tests/unit/recommenders/evaluation/test_python_evaluation.py#L47) for the test.

**Review by miguelgfierro — APPROVED** [review]
This is good progress @chuyangke. I agree with Simon, it would be great to have the tests. This can be done in this PR or in a different one, depending on what you prefer.

In another PR you maybe can explore how to perform the same operation with numpy, hopefully this gives us a much better time. 
Some code I found in the web:
- with argpartition: https://stackoverflow.com/questions/43386432/how-to-get-indexes-of-k-maximum-values-from-a-numpy-multidimensional-array
- groupby with numpy (maybe the other method is better): https://cmdlinetips.com/2019/05/how-to-implement-pandas-groupby-operation-with-numpy/

**Comment by ChuyangKe** [comment]
> This is good progress @ChuyangKe. I agree with Simon, it would be great to have the tests. This can be done in this PR or in a different one, depending on what you prefer. Please let Simon and me know.
> 
> In another PR you maybe can explore how to perform the same operation with numpy, hopefully this gives us a much better time. Some code I found in the web:
> 
> * with argpartition: https://stackoverflow.com/questions/43386432/how-to-get-indexes-of-k-maximum-values-from-a-numpy-multidimensional-array
> * groupby with numpy (maybe the other method is better): https://cmdlinetips.com/2019/05/how-to-implement-pandas-groupby-operation-with-numpy/

I will create another PR for the test case @simonzhaoms @miguelgfierro. 

Just wanted to make sure @miguelgfierro, do you mean implementing the same function get_top_k_items() using numpy (instead of current pandas operations), or is it another function?

**Comment by miguelgfierro** [comment]
> do you mean implementing the same function get_top_k_items() using numpy (instead of current pandas operations), or is it another function?

get_top_k_items() using numpy

I'll merge this, super good @ChuyangKe! keep up the good work

**Pull request merged**
