### PR TITLE
added seed

### PR DESCRIPTION
**Pull request by miguelgfierro**
### Description

Added seed in TF algos.

In the smoke and integration tests we have been seeing a lot of variability. Let's see if this solves the issue

### Checklist:

- [x] My code follows the code style of this project, as detailed in our [contribution guidelines](../CONTRIBUTING.md).
- [ ] I have added tests.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by msalvaris** [comment]
@miguelgfierro [j/k]The industry standard for random seed is 42 (https://en.wikipedia.org/wiki/42_(number)) :D

**Comment by miguelgfierro** [comment]
That's a good point. I'll change all the seeds for the Answer to the Ultimate Question of Life, the Universe, and Everything
:-) :-)

**Comment by AaronHeee** [comment]
> That's a good point. I'll change all the seeds for the Answer to the Ultimate Question of Life, the Universe, and Everything
> :-) :-)

Hi, I have added random seed (mentioned in #388 ), but the seed looks not working. So, should I add more random seeds in TF?

**Comment by miguelgfierro** [comment]
hey @AaronHeee I added a random seed here: https://github.com/Microsoft/Recommenders/blob/cec5efadcc4b1c2df4247b1e8a9f284da8fe0db5/reco_utils/recommender/ncf/ncf_singlenode.py

If you think this is ok, please accept, if you think there is anything else that needs to be done, please let us know

**Comment by AaronHeee** [comment]
hello @miguelgfierro, thanks, it works for me.

**Pull request merged**
