### PR TITLE
added papermill documentation

### PR DESCRIPTION
**Pull request by miguelgfierro**
### Description

Explain how to add papermill tests to the notebooks

### Releated Issues
https://github.com/Microsoft/Recommenders/issues/455

### Checklist:

- [x] My code follows the code style of this project, as detailed in our [contribution guidelines](../CONTRIBUTING).
- [ ] I have added tests.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by heatherbshapiro** [comment]
It might be helpful to link to/ or show a simple test in the repo, showing what you've stated with adding parameters

**Comment by miguelgfierro** [comment]
hey @bethz @heatherbshapiro just one comment on how the team review and provide feedback. Normally, developers will review the code and add comments inline or in the main chat. Latelly, for notebooks we are using ReviewNB https://app.reviewnb.com/Microsoft/Recommenders/. 

The review of the developer can have 3 states: accept, reject and comment.
1) Accept means that as developer I think that the code is good to get into the repo. If I just add a minor comments, and I don't want to review again this code again, I still accept.
2) Comment means that I ask some questions or suggest changes and I expect some changes that I will review again. There is no explicit acceptance or rejection here, we are just discussing.
3) Reject means that there is something really wrong in the code. We use this action very few times. If I reject something I'm stopping anyone for merging. It could be that the code is not running or the code is breaking our contribution guidelines in a hard way.

For anyone to merge the code, at least there has to be 1 accept.

**Comment by heatherbshapiro** [comment]
A few other comments/questions:

1. I had to reinstall papermill when testing this - for some reason it did not get installed in the conda enviroment
2. When i try to create a python script with the provided code, I get the error that tests.notebooks_common does not exist, do I need to put this file in a specific directory?
`ImportError while importing test module 'C:\Users\hshapiro\Documents\Recommenders\notebooks\00_quick_start\test_unit_my_notebook.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
notebooks\00_quick_start\test_unit_my_notebook.py:3: in <module>
    from tests.notebooks_common import OUTPUT_NOTEBOOK, KERNEL_NAME
E   ModuleNotFoundError: No module named 'tests.notebooks_common'`
3. Mentioned above - It would be helpful to link to an example test that uses the parameters/ ideas that are being spoken about or show them inline
4. I think it would be good to separate the unit and smoke/integration tests into a separate beginner/ advanced sections with headers

**Comment by miguelgfierro** [comment]
hey @heatherbshapiro I made several changes following your suggestions. 

I tried the environment generating a new conda file and papermill works. As of now, there is a bug in the generation file https://github.com/Microsoft/Recommenders/issues/488, if you have problems installing the libraries please let me know.

**Comment by heatherbshapiro** [comment]
@miguel-ferreira I believe @bethz question was around why there is a message string to pass in the parameters instead of feature flags like --notebook --spark --gpu:

`pytest tests/unit -m "not notebooks and not spark and not gpu"`

**Comment by miguelgfierro** [comment]
oh I see, good question. This is the way tests are marked in pytest, see this https://docs.pytest.org/en/latest/example/markers.html

**Pull request merged**
