### PR TITLE
Update description

### PR DESCRIPTION
**Pull request by miguelgfierro**
### Checklist:

- [ ] I have followed the [contribution guidelines](../CONTRIBUTING.md) and code style for this project.
- [ ] I have added tests covering my contributions.
- [ ] I have updated the documentation accordingly.
- [ ] This PR is being made to `staging branch` and not to `main branch`.

### CODE REVIEW

**Review by anargyri — APPROVED** [review]

**Comment by wutaomsft** [comment]
We should add Summary which is a mandatory field based on https://www.python.org/dev/peps/pep-0314

**Comment by anargyri** [comment]
> We should take a look at https://packaging.python.org/specifications/core-metadata/ too, which include "Summary".

I don't think these specs map exactly to the `setup()` keywords, for example "summary" is missing, see https://setuptools.readthedocs.io/en/latest/references/keywords.html

**Comment by miguelgfierro** [comment]
I was looking at the summary field, and according to [this](https://github.com/microsoft/malmo/blob/master/scripts/python-wheel/package/setup.py#L47), the [summary field in the metadata](https://packaging.python.org/specifications/core-metadata/#summary) corresponds to the description in setup.py. And the [description field in the metadata](https://packaging.python.org/specifications/core-metadata/#description) corresponds with long_description in setup.py. 

Right now we have the description in setup.py, however, we don't have a long summary. Not sure if people want to add that

**Comment by anargyri** [comment]
> I was looking at the summary field, and according to [this](https://github.com/microsoft/malmo/blob/master/scripts/python-wheel/package/setup.py#L47), the [summary field in the metadata](https://packaging.python.org/specifications/core-metadata/#summary) corresponds to the description in setup.py. And the [description field in the metadata](https://packaging.python.org/specifications/core-metadata/#description) corresponds with long_description in setup.py.
> 
> Right now we have the description in setup.py, however, we don't have a long summary. Not sure if people want to add that

No, we have both description and long_description in `setup.py`.

**Comment by miguelgfierro** [comment]
that's right, so then I think we are ok with this

**Pull request merged**
