### PR TITLE
Adding load test for ALS movie recommender model

### PR DESCRIPTION
**Pull request by nikhilrj**
### Description
Adding Azure DevOps load test configuration for operationalized AKS model. 

### Checklist:

- [x] My code follows the code style of this project, as detailed in our [contribution guidelines](../CONTRIBUTING.md).
- [ ] I have added tests.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by yueguoguo** [comment]
+1 on making this clear in a README. It is using a language and technology stack that may be not familiar to most of the audience. It would be great to describe some details about this.

**Comment by gramhagen** [comment]
in the past I've used [locust](https://locust.io/), has the advantage of being easy to setup and deply and python based

**Comment by miguelgfierro** [comment]
how easy is locust as a comparison to the C# option?

**Comment by gramhagen** [comment]
may be easier to leverage something like what they've done here: https://github.com/Microsoft/AKSDeploymentTutorialAML/blob/master/%7B%7Bcookiecutter.project_name%7D%7D/Keras_Tensorflow/aks/06_SpeedTestWebApp.ipynb

**Comment by gramhagen** [comment]
closing this as it relies on deprecated tooling: https://docs.microsoft.com/en-us/visualstudio/test/quickstart-create-a-load-test-project?view=vs-2019

we can leverage something like #758 for ALS too

**Pull request closed without merging**
