### PR TITLE
Rearrange README and SETUP files; add info about pip install 

### PR DESCRIPTION
**Pull request by anargyri**
### Description

- Separated the part about conda and yaml files from the setup requirements into a new Markdown file.
- Replaced references to conda envs with more general envs.
- Added references to pip installation in the setup guide.

### Checklist:

- [ ] I have followed the [contribution guidelines](../CONTRIBUTING.md) and code style for this project.
- [ ] I have added tests covering my contributions.
- [ ] I have updated the documentation accordingly.
- [ ] This PR is being made to `staging branch` and not to `main branch`.

### CODE REVIEW

**Comment by miguelgfierro** [comment]
We have right now 3 places with dependencies, the old conda file, the setup.py and docs/requirements.txt. And also, two ways of installing, with pip and with conda. 

Maybe we can consider the advantages/disadvantages of having this versus having 1 single place where we have all deps and only installation with pip. Do you guys think this is possible?

**Comment by gramhagen** [comment]
yeah, i agree it will be best if we can consolidate around using pip install for dependencies and remove the conda setup, should we capture this in a new issue?

**Comment by anargyri** [comment]
> yeah, i agree it will be best if we can consolidate around using pip install for dependencies and remove the conda setup, should we capture this in a new issue?

Yes, feel free to create an issue around this. Let's leave it though for after publication on PyPI.

**Review by miguelgfierro — APPROVED** [review]
merging this, we'll review in the future if needed

**Pull request merged**
