### PR TITLE
fix: Change formats of user_ids and item_ids arg.

### PR DESCRIPTION
**Pull request by ywkim92**
### Description

ML model predicts the rating for an user inside `prepare_all_prediction` function.
But if I run the current code, the following error occurs:
`TypeError: Invalid type passed to user_ids parameter. This must be either int or np.int32 array. Type received: <class 'numpy.int64'>` 
To fix this error,
1. the types of `user_ids`[link](https://github.com/microsoft/recommenders/blob/60033231b9167438032843c23158c0c776856e0e/recommenders/models/lightfm/lightfm_utils.py#L259) should be changed from int to np.int32 array
2. the types of `item_ids`[link](https://github.com/microsoft/recommenders/blob/60033231b9167438032843c23158c0c776856e0e/recommenders/models/lightfm/lightfm_utils.py#L260) should be changed from list to np.int32 array

### Related Issues

I haven't found yet.

### Checklist:

- [x] I have followed the [contribution guidelines](../CONTRIBUTING.md) and code style for this project.
- [x] I have added tests covering my contributions.
- [x] I have updated the documentation accordingly.
- [x] This PR is being made to `staging branch` and not to `main branch`.

### CODE REVIEW

**Comment by gramhagen** [comment]
should we add the dtype to ensure it's np.int32?
e.g.: np.array(x["uid"], dtype=np.int32)

**Review by gramhagen — APPROVED** [review]

**Review by miguelgfierro — APPROVED** [review]
@ywkim92 this is great, thanks, however there is a conflict in the code so we can't merge, can you please review?

**Comment by SafetyMary** [comment]
May i know if the issue has been fixed?
I tried running the lightFM quick start notebook (https://github.com/microsoft/recommenders/blob/main/examples/02_model_hybrid/lightfm_deep_dive.ipynb)
and got the error on 

with Timer() as test_time:
    all_predictions = prepare_all_predictions(data, uid_map, iid_map, 
                                              interactions=train_interactions,
                                              model=model1, 
                                              num_threads=NO_THREADS)

TypeError: Invalid type passed to user_ids parameter. This must be either int or np.int32 array. Type received: <class 'numpy.int64'>

System version: 3.8.13 (default, Mar 28 2022, 06:59:08) [MSC v.1916 64 bit (AMD64)]
LightFM version: 1.16

**Comment by miguelgfierro** [comment]
[SafetyMary](https://github.com/SafetyMary) if you install recommenders from main, the code in this PR should be in. We will do a release in PyPI soon that will include this

**Comment by SafetyMary** [comment]
Have updated to the lastest 1.1.0 ver through pip but the issue still presists.

**Pull request merged**
