### PR TITLE
TEST: revert to the old aml test pipeline yeaml

### PR DESCRIPTION
**Pull request by yueguoguo**
### Description
Remove the added arguments that take custom Docker images from private registy

### Checklist:

- [ ] I have followed the [contribution guidelines](../CONTRIBUTING.md) and code style for this project.
- [ ] I have added tests covering my contributions.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by gramhagen** [comment]
Why are these being reverted?

**Comment by yueguoguo** [comment]
@gramhagen ah I should say this is something temporary for now because we are using the DSVM-based testing pipeline. Later on we can get them back when revisiting the AzureML based testing pipeline. Does it make sense?

**Comment by gramhagen** [comment]
I thought we were just disabling them?

**Comment by yueguoguo** [comment]
Ah the reverted part is the unfinished ones that incorporate customized Docker images into the AzureML testing pipeline which are currently not working. I am thinking keeping the original AzureML testing pipeline that works, regardless where the resources are located, and later on when necessary, adding them back.

**Comment by yueguoguo** [comment]
One thing I am not sure about is that even if I disabled the triggers of some pipelines in Azure Pipelines, they are still detected here and run when a new PR is submitted... 😢

**Comment by gramhagen** [comment]
I see. Well if you need to remove them altogether we can always get them back from the history.

**Pull request merged**
