### PR TITLE
Update multinomial_vae.py

### PR DESCRIPTION
**Pull request by kone807**
corrected import for Adam optimizer

### Checklist:

- [ ] I have followed the [contribution guidelines](../CONTRIBUTING.md) and code style for this project.
- [ ] I have added tests covering my contributions.
- [ ] I have updated the documentation accordingly.
- [ ] This PR is being made to `staging branch` and not to `main branch`.

### CODE REVIEW

**Comment by miguelgfierro** [comment]
hi @kone807, does this fix https://github.com/microsoft/recommenders/issues/1915?

**Comment by kone807** [comment]
hey @miguelgfierro, this and changing line 294 by adding legacy before adam in recommenders/models/vae/standard_vae.py fixes the errors and the code executes correctly with proper results.

**Comment by miguelgfierro** [comment]
do you want to push the change in the file `standard_vae.py` as well?

**Comment by kone807** [comment]
@microsoft-github-policy-service agree 

@miguelgfierro committed the changes. The current version works fine at my end, for both standard vae and multi vae

**Pull request merged**
