### PR TITLE
Rerun and clean notebooks with Python 3.9

### PR DESCRIPTION
**Pull request by miguelgfierro**
### Checklist:

- [ ] I have followed the [contribution guidelines](../CONTRIBUTING.md) and code style for this project.
- [ ] I have added tests covering my contributions.
- [ ] I have updated the documentation accordingly.
- [ ] This PR is being made to `staging branch` and not to `main branch`.

### CODE REVIEW

**Comment by anargyri** [comment]
Any idea why these value counts changed? The data set should be the same, shouldn't it? So value counts should remain the same too. 

_Respond and view the context [here](https://gitnotebooks.com/microsoft/recommenders/pull/1947#comment-120)._

**Comment by anargyri** [comment]
This looks fishy, the logloss should be the same, since ground truth and predictions have not changed. 

_Respond and view the context [here](https://gitnotebooks.com/microsoft/recommenders/pull/1947#comment-121)._

**Comment by anargyri** [comment]
Same here.

_Respond and view the context [here](https://gitnotebooks.com/microsoft/recommenders/pull/1947#comment-122)._

**Comment by miguelgfierro** [comment]
fixed in the next commit

_Respond and view the context [here](https://gitnotebooks.com/microsoft/recommenders/pull/1947#comment-124)._

**Comment by miguelgfierro** [comment]
fixed by reruning

_Respond and view the context [here](https://gitnotebooks.com/microsoft/recommenders/pull/1947#comment-125)._

**Comment by miguelgfierro** [comment]
this is weird, I looked at the history of this file and 4.1 was obtained the first time it was computed years ago. I have rerun the notebook with python 3.9 and sklearn 1.0.2 and I get 5.25. I have also tried python 3.8 and sklearn 0.24.2 and I got the same result. I don't know, maybe the first time was wrong?

_Respond and view the context [here](https://gitnotebooks.com/microsoft/recommenders/pull/1947#comment-126)._

**Review by miguelgfierro — COMMENTED** [review]
@anargyri I have reviewed the comments and fixed what you mentioned. I couldn't find a fix for the logloss, see my comments

**Comment by miguelgfierro** [comment]
I don't understand very well why the SAR notebooks are not passing. They were passing beofre, we are getting the same error in the other PRs, but for example, in this one, we haven't touched that file. 
It works in local

**Comment by anargyri** [comment]
Ok, it may have been a bad output that was somehow left there.

_Respond and view the context [here](https://gitnotebooks.com/microsoft/recommenders/pull/1947#comment-136)._

**Comment by anargyri** [comment]
> I don't understand very well why the SAR notebooks are not passing. They were passing beofre, we are getting the same error in the other PRs, but for example, in this one, we haven't touched that file. It works in local

It looks like the sparse matrix product causes this error https://github.com/microsoft/recommenders/actions/runs/5392089967/jobs/9789938422?pr=1947#step:3:2468
Maybe something changed in a more recent version of scipy?

**Comment by anargyri** [comment]
> > I don't understand very well why the SAR notebooks are not passing. They were passing beofre, we are getting the same error in the other PRs, but for example, in this one, we haven't touched that file. It works in local
> 
> It looks like the sparse matrix product causes this error https://github.com/microsoft/recommenders/actions/runs/5392089967/jobs/9789938422?pr=1947#step:3:2468 Maybe something changed in a more recent version of scipy? Or maybe the sparse matrices are not computed correctly? You may need to check what the matrices are. Did you try this test on a VM?

I tried it on a VM and it fails with this error.

**Comment by miguelgfierro** [comment]
That's interesting, in my local computer it passes.
These are the versions I have:
```
System version: 3.9.16 (main, May 15 2023, 23:46:34) 
[GCC 11.2.0]
Pandas version: 1.5.3
NumPy version: 1.24.3
Scipy version: 1.10.1
```
Can you check the ones where it breaks @anargyri?

**Comment by anargyri** [comment]
> That's interesting, in my local computer it passes. These are the versions I have:
> 
> ```
> System version: 3.9.16 (main, May 15 2023, 23:46:34) 
> [GCC 11.2.0]
> Pandas version: 1.5.3
> NumPy version: 1.24.3
> Scipy version: 1.10.1
> ```
> 
> Can you check the ones where it breaks @anargyri?

Python and pandas versions are the same, numpy is 1.24.4, scipy is 1.11.0 , gcc is 9.4.0.

**Comment by anargyri** [comment]
> > That's interesting, in my local computer it passes. These are the versions I have:
> > ```
> > System version: 3.9.16 (main, May 15 2023, 23:46:34) 
> > [GCC 11.2.0]
> > Pandas version: 1.5.3
> > NumPy version: 1.24.3
> > Scipy version: 1.10.1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Can you check the ones where it breaks @anargyri?
> 
> Python and pandas versions are the same, numpy is 1.24.4, scipy is 1.11.0 , gcc is 9.4.0.

It could be related to this change https://scipy.github.io/devdocs/reference/sparse.html#module-scipy.sparse

**Comment by miguelgfierro** [comment]
@anargyri the issue with scipy is fixed, I'm reruning the tests, hopefuly they pass. Please review.

**Review by anargyri — APPROVED** [review]

**Pull request merged**
