### PR TITLE
Merge from staging to main for release 0.7.0

### PR DESCRIPTION
**Pull request by anargyri**
### Checklist:

- [x] I have followed the [contribution guidelines](../CONTRIBUTING.md) and code style for this project.
- [x] I have added tests covering my contributions.
- [x] I have updated the documentation accordingly.
- [ ] This PR is being made to `staging branch` and not to `main branch`.

### CODE REVIEW

**Review by gramhagen — APPROVED** [review]

**Comment by miguelgfierro** [comment]
There is this error:
```
    @pytest.mark.notebooks
    @pytest.mark.gpu
    def test_gpu_vm():
>       assert get_number_gpus() >= 1
E       assert 0 >= 1
E        +  where 0 = get_number_gpus()
```
@anargyri do you know what the problem could be?

**Comment by anargyri** [comment]
> There is this error:
> 
> ```
>     @pytest.mark.notebooks
>     @pytest.mark.gpu
>     def test_gpu_vm():
> >       assert get_number_gpus() >= 1
> E       assert 0 >= 1
> E        +  where 0 = get_number_gpus()
> ```
> 
> @anargyri do you know what the problem could be?

I saw this problem in the last PR too. Maybe something with the CUDA configuration not working properly?

**Comment by gramhagen** [comment]
> > There is this error:
> > ```
> >     @pytest.mark.notebooks
> >     @pytest.mark.gpu
> >     def test_gpu_vm():
> > >       assert get_number_gpus() >= 1
> > E       assert 0 >= 1
> > E        +  where 0 = get_number_gpus()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @anargyri do you know what the problem could be?
> 
> I saw this problem in the last PR too. Maybe something with the CUDA configuration not working properly on the GPU machine?

@laserprec can you look into this?

**Comment by anargyri** [comment]
> > > There is this error:
> > > ```
> > >     @pytest.mark.notebooks
> > >     @pytest.mark.gpu
> > >     def test_gpu_vm():
> > > >       assert get_number_gpus() >= 1
> > > E       assert 0 >= 1
> > > E        +  where 0 = get_number_gpus()
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > @anargyri do you know what the problem could be?
> > 
> > 
> > I saw this problem in the last PR too. Maybe something with the CUDA configuration not working properly on the GPU machine?
> 
> @laserprec can you look into this?

It's just a problem with nvidia driver updates happening on VMs. nvidia-smi fails after that and you need to reboot the machine.

**Comment by laserprec** [comment]
> > > > There is this error:
> > > > ```
> > > >     @pytest.mark.notebooks
> > > >     @pytest.mark.gpu
> > > >     def test_gpu_vm():
> > > > >       assert get_number_gpus() >= 1
> > > > E       assert 0 >= 1
> > > > E        +  where 0 = get_number_gpus()
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > @anargyri do you know what the problem could be?
> > > 
> > > 
> > > I saw this problem in the last PR too. Maybe something with the CUDA configuration not working properly on the GPU machine?
> > 
> > 
> > @laserprec can you look into this?
> 
> It's just a problem with nvidia driver updates happening on VMs. nvidia-smi fails after that and you need to reboot the machine.

The machines are rebooted and it should be resolved.
Turns out there's a new nvidia-driver update this weekend:

>> cat /var/log/apt/history.log
....
Start-Date: 2021-09-10  06:51:06
Commandline: /usr/bin/unattended-upgrade
Upgrade: libnvidia-compute-470:amd64 (470.57.02-0ubuntu1, 470.63.01-0ubuntu0.18.04.2)

**Pull request merged**
