### PR TITLE
[TEST] Triggering the ADO tests

### PR DESCRIPTION
**Pull request by miguelgfierro**
### Description

This is a test to understand why the ADO tests in the PR https://github.com/microsoft/recommenders/pull/1565 are not being triggered

### Checklist:

- [ ] I have followed the [contribution guidelines](../CONTRIBUTING.md) and code style for this project.
- [ ] I have added tests covering my contributions.
- [ ] I have updated the documentation accordingly.
- [ ] This PR is being made to `staging branch` and not to `main branch`.

### CODE REVIEW

**Comment by miguelgfierro** [comment]
image
@anargyri I found out that [the tests in ADO are being executed](https://dev.azure.com/best-practices/recommenders/_settings/agentqueues?queueId=93&view=jobs), and they all pass. However, the unit tests don't appear in the Github options, only the ones with notebooks. Also, if we go to settings the unit tests are not listed, I can't even find them: https://github.com/microsoft/recommenders/settings/branch_protection_rules/6371109

**Comment by miguelgfierro** [comment]
@anargyri in addition, some of the the Github action tests are breaking. For example, the GPU one [fails because numba is not detecting a GPU](https://github.com/microsoft/recommenders/runs/4393144000?check_suite_focus=true). FYI @laserprec any idea what could be happening?

**Comment by anargyri** [comment]
> @anargyri in addition, some of the the Github action tests are breaking. For example, the GPU one [fails because numba is not detecting a GPU](https://github.com/microsoft/recommenders/runs/4393144000?check_suite_focus=true). FYI @laserprec any idea what could be happening?

There is no cuda 11 installed on the GitHub hosts. I will add new hosts that have cuda 11.

**Comment by anargyri** [comment]
I think I fixed it with the last PR. Tests are passing here https://dev.azure.com/best-practices/recommenders/_settings/agentqueues?queueId=93&view=jobs

**Comment by anargyri** [comment]
In a couple of hours we can also check if the badge goes green.

**Comment by anargyri** [comment]
There is a warning in https://dev.azure.com/best-practices/recommenders/_build/results?buildId=54454&jobId=a2bd9722-611a-5a1a-49b7-b5d4cc326141&view=results about status of runs not being reported.

"Failed to post status to GitHub for repository microsoft/recommenders with error: "Not Found". Verify that the GitHub credentials are still valid on the service connection. For OAuth connections, verify that Azure Pipelines is granted access to the repository's organization https://go.microsoft.com/fwlink/?linkid=2019209"

The link takes me to the OAuth allowed apps. I don't see Azure Pipelines though. What do you see at this link?

**Comment by miguelgfierro** [comment]
image
this is what I see, do you see the same?

I can try to revoke the access and try to connect again?

**Comment by anargyri** [comment]
> image this is what I see, do you see the same?
> 
> I can try to revoke the access and try to connect again?

I don't see this because the link takes me to my personal GitHub. But if you see it then the settings should be ok, shouldn't they?

**Comment by anargyri** [comment]
ADO tests have altogether disappeared from the checks.

**Comment by miguelgfierro** [comment]
> ADO tests have altogether disappeared from the checks.

this is weird and annoying. Maybe we can wait until Pradnyesh finish the AzureML tests and remove all this altogether?

**Comment by miguelgfierro** [comment]
closing this, because it was an old test

**Pull request closed without merging**
